#!/bin/sh
# Kevin Weldon - 01/23
# echo on
set -x

GENERATE_SIM_SCRIPTS=1
RUN_MODELSIM=1
OPEN_MODELSIM=1

PROJECT=top
REVISION=top
SIMULATION_DIRECTORY=simulation
SIM_SCRIPTS=./sim_scripts

if [ $GENERATE_SIM_SCRIPTS == 1 ]
then
    # Generate IP
    cd ../; ip-setup-simulation --quartus-project=$PROJECT --revision=$REVISION --output-directory=$SIM_SCRIPTS --compile-to-work --use-relative-paths; cd $SIMULATION_DIRECTORY;
fi

if [ $RUN_MODELSIM == 1 ]
then
    # Remove current wlf file
    rm -f vsim.wlf
    # Run simulation in ModelSim
    vsim -c -do 'source run_sim.tcl'
    # Copy simpulation transcript prior to opening Modelsim
    cp transcript sim_transcript
    if [ $OPEN_MODELSIM == 1 ]
    then
	vsim -gui -view vsim.wlf -do 'wave.do'
    fi
fi

# echo off
set +x
